version: 2.1

commands:
  yarn-dependencies:
    description: 'Get JavaScript dependencies'
    steps:
      - restore_cache:
          name: Restore yarn cache
          key: key-{{ .Environment.CACHE_VERSION }}-yarn-lib-{{ checksum "./yarn.lock" }}-{{ arch }}
      - run:
          working_directory: .
          name: Installing lib dependencies
          command: yarn install
      - save_cache:
          name: Cache
          key: key-{{ .Environment.CACHE_VERSION }}-yarn-lib-{{ checksum "./yarn.lock" }}-{{ arch }}
          paths:
            - ././node_modules
      - run:
          working_directory: .
          name: run jest test
          command: yarn test
      - restore_cache:
          name: Restore yarn app-example cache
          key: key-{{ .Environment.CACHE_VERSION }}-yarn-app-{{ checksum "./example/yarn.lock" }}-{{ arch }}
      - run:
          working_directory: ./example
          name: Installing app-example dependencies
          command: yarn install
      - save_cache:
          name: Save yarn app-example cache
          key: key-{{ .Environment.CACHE_VERSION }}-yarn-app-{{ checksum "./example/yarn.lock" }}-{{ arch }}
          paths:
            - ././node_modules
  pods-dependencies:
    description: 'Get cocoapods dependencies'
    steps:
      - restore_cache:
          name: Restore cache pods
          key: key-{{ .Environment.CACHE_VERSION }}-cocoapods-{{ checksum "./example/ios/Podfile.lock" }}-{{ arch }}
      - run:
          name: Install pods
          working_directory: ./example/ios
          command: pod install
      - save_cache:
          name: Cache pods
          key: key-{{ .Environment.CACHE_VERSION }}-cocoapods-{{ checksum "./example/ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ./example/ios/Pods
            - ~/.cocoapods


jobs:
  ios-test:
    macos:
      xcode: 14.3.1
    steps:
      - attach_workspace:
          at: .
      - checkout
      - yarn-dependencies
      - pods-dependencies
      - run:
          name: 'Install applesimutils'
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew && HOMEBREW_NO_AUTO_UPDATE=1  brew install applesimutils; applesimutils --list
      - run:
          name: Clear detox cache
          working_directory: ./example
          command: npx detox clean-framework-cache && npx detox build-framework-cache
      - run:
          name: Run iOS detox build
          working_directory: ./example
          command: npx detox build -c ios.sim.debug
      - run:
          name: Run iOS detox test
          working_directory: ./example
          command: npx detox test -c ios.sim.debug

workflows:
  run_detox_tests:
    jobs:
      - ios-test
